### ISSUE TITLE
Django Project Initialization

### ISSUE THREAD

**Issue by ShenalSen** [ShenalSen/OncoDetect#3]
### **Description**  
Set up the foundational backend structure for the OncoDetect project using the Django framework. This task involves initializing the Django project, configuring the virtual environment, and preparing the essential folder structure.

---

### **Implementation Steps**  

1. **Create a Virtual Environment**  
   - Use `venv` or `conda` to isolate the project dependencies.  
   - Commands:  
     - For `venv`:  
       ```bash
       python -m venv env
       source env/bin/activate   # On Mac/Linux
       .\env\Scripts\activate    # On Windows
       ```  
     - For `conda`:  
       ```bash
       conda create -n oncodetect_env python=3.12
       conda activate oncodetect_env
       ```  

2. **Initialize Django Project**  
   - Install Django and Django REST Framework (DRF):  
     ```bash
     pip install django djangorestframework
     ```  
   - Start a new Django project named **OncoDetectBackend**:  
     ```bash
     django-admin startproject OncoDetectBackend
     ```  
   - Navigate to the project folder and run the development server to test:  
     ```bash
     cd OncoDetectBackend
     python manage.py runserver
     ```

3. **Set Up Essential Folder Structure**  
   - Create core Django apps as needed. For example:  
     ```bash
     python manage.py startapp core
     python manage.py startapp patients
     ```  
   - Update the `INSTALLED_APPS` in `settings.py` to include the new apps:  
     ```python
     INSTALLED_APPS = [
         'django.contrib.admin',
         'django.contrib.auth',
         ...
         'rest_framework',   # Django REST Framework
         'core',             # Core functionalities
         'patients',         # Patients app
     ]
     ```

4. **Organize Folder Structure**  
   Follow a clean structure like this:  
   ```
   OncoDetectBackend/
   ├── OncoDetectBackend/       # Project settings
   ├── core/                    # Core app
   ├── patients/                # Patients app
   ├── manage.py                # Entry point
   ├── requirements.txt         # Project dependencies
   └── README.md                # Documentation
   ```  

5. **Install and Freeze Requirements**  
   - Freeze all installed dependencies to a `requirements.txt` file:  
     ```bash
     pip freeze > requirements.txt
     ```  

6. **Run Server and Verify Setup**  
   - Run the development server:  
     ```bash
     python manage.py runserver
     ```  
   - Open a browser and visit: `http://127.0.0.1:8000/` to confirm the setup.

---

### **Tips and Tricks**  
- **Virtual Environment Activation**: Always ensure the virtual environment is activated before installing packages.  
- **Avoid Common Pitfalls**:  
  - Missing `__init__.py` files in apps or folders can cause import errors.  
  - Use descriptive names for apps, e.g., `patients` instead of `app1`.  
- **Dependency Management**: Use `requirements.txt` to keep track of project dependencies.  

---

### **Acceptance Criteria**  
- [x] Virtual environment is created and activated.  
- [x] Django project is initialized and runs without errors.  
- [x] Folder structure follows the recommended format.  
- [x] Essential libraries like `Django` and `DRF` are installed.  
- [x] The `requirements.txt` file is created and up-to-date.
